### ISSUE TITLE
litex.soc.doc generation error

### ISSUE THREAD

**Issue by gregdavill** [litex-hub/litespi#61]
I'm updating some older icebreaker litex examples to use more upstream LiteX features. One of which is LiteSPI
The SoC works, as expected, but it appears I'm no longer able to generate documentation... 

I've been able to replicate this in the `litex_boards.1bitsquared_icebreaker` target. 
```diff
diff --git a/litex_boards/targets/1bitsquared_icebreaker.py b/litex_boards/targets/1bitsquared_icebreaker.py
index 0ab0434..a2c0daf 100755
--- a/litex_boards/targets/1bitsquared_icebreaker.py
+++ b/litex_boards/targets/1bitsquared_icebreaker.py
@@ -160,6 +160,9 @@ def main():
     builder = Builder(soc, **builder_argdict(args))
     builder.build(run=args.build)
 
+    from litex.soc.doc import generate_docs
+    generate_docs(soc, "build/docs/")
+
     if args.load:
         prog = soc.platform.create_programmer()
         prog.load_bitstream(os.path.join(builder.gateware_dir, soc.build_name + ".bin"))
```

Then running creates the following error.
```
$ ./1bitsquared_icebreaker.py

--- snip ---

Traceback (most recent call last):
  File "/home/greg/Projects/icebreaker-litex-examples/soc/deps/litex-boards/litex_boards/targets/1bitsquared_icebreaker.py", line 174, in <module>
    main()
  File "/home/greg/Projects/icebreaker-litex-examples/soc/deps/litex-boards/litex_boards/targets/1bitsquared_icebreaker.py", line 164, in main
    generate_docs(soc, "build/docs/")
  File "/home/greg/Projects/icebreaker-litex-examples/soc/deps/litex/litex/soc/doc/__init__.py", line 99, in generate_docs
    documented_region = DocumentedCSRRegion(
  File "/home/greg/Projects/icebreaker-litex-examples/soc/deps/litex/litex/soc/doc/csr.py", line 80, in __init__
    docs = module.get_module_documentation()
  File "/home/greg/Projects/icebreaker-litex-examples/soc/deps/litex/litex/soc/integration/doc.py", line 141, in gatherer
    return sorted(r, key=lambda x: x.duid)
  File "/home/greg/Projects/icebreaker-litex-examples/soc/deps/litex/litex/soc/integration/doc.py", line 141, in <lambda>
    return sorted(r, key=lambda x: x.duid)
  File "/home/greg/Projects/icebreaker-litex-examples/soc/deps/migen/migen/fhdl/module.py", line 136, in __getattr__
    raise AttributeError("'"+self.__class__.__name__+"' object has no attribute '"+name+"'")
AttributeError: 'LiteSPISDRPHYCore' object has no attribute 'duid'
```

**Comment by mithro** [comment]
@kgugala - Who added this code and thus should look at this issue?

**Comment by Disasm** [comment]
Probably `LiteSPISDRPHYCore` should be somehow excluded from the parent one, otherwise litex generates docs both for the parent one and (twice) for the inner one. This would also solve the problem with this module.

Another question is why this hack is required (actually setting `self.duid` is enough). Probably it's a bug in an unrelated part of litex, because other modules with a similar structure don't reveal any problems.
